apiVersion: v1
kind: Service
metadata:
  name: springboot-app-nodeport
  namespace: koteswararao-namespace
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080       # Service port inside cluster
      targetPort: 8080 # Pod port
      nodePort: 30081  # External port to access from outside
