apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello
  namespace: koteswararao-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
      - name: springboot-hello
        image: koti02/springboot-app:latest   # ✅ Correct Spring Boot image
        ports:
        - containerPort: 8080
